version: "3.9"
services:
  potatis:
    build:
      context: ..
      dockerfile: nes-cloud/Dockerfile
    ports:
      - "4444:4444"
      - "5555:5555"
      - "6666:6666"
      - "7777:7777"
  restart: unless-stopped